### ISSUE TITLE
getChrono

### ISSUE THREAD

**Issue by jeanclaudeb** [AntoineAugusti/diplo#1]
Ajouter la possibilité de récupérer le temps restant pour le client durant la phase de négociations.

**Comment by ThibaudDauce** [comment]
Normallement c'est déjà documenté.

**Comment by AntoineAugusti** [comment]
Indiqué dans cette méthode : https://developers.diplo-lejeu.fr/diplo/1.0/endpoints/parties/GET_parties_id_phase
