### ISSUE TITLE
Récupérer armées possédées par un joueur

### ISSUE THREAD

**Issue by manonansart** [AntoineAugusti/diplo#10]
Y a-t-il moyen de connaitre toute les armées possédées par un joueur, ou de savoir à quel joueur appartient une armée ?

**Comment by AntoineAugusti** [comment]
Il va manquer une méthode pour faire ça. Du style GET parties/:id/armees

**Comment by jeanclaudeb** [comment]
Est-ce qu'il serait possible d'avoir un symbole associé aux armées d'un joueur ? Du style un caractère unicode comme \u2605 ?

**Comment by AntoineAugusti** [comment]
@jeanclaudeb C'est vraiment propre à l'UI, je pense pas que ça ait sa place dans l'API. Tu peux générer un caractère unicode unique par joueur à partir de son ID. Je pense que c'est une feature à faire uniquement côté client.

**Comment by jeanclaudeb** [comment]
Ok ça marche !

**Comment by etiennebatise** [comment]
En attente de validation 
- https://github.com/AntoineAugusti/diplo/commit/df2065cf35b99b279b4665460b90415d5986823b

Il va falloir coder aussi cette méthode dans **PartiesController.php**

**Comment by AntoineAugusti** [comment]
@etiennebatise Je n'avais pas vu que tu n'avais pas rajouté ça dans "l'introduction" de l'API et la TOC. https://github.com/AntoineAugusti/diplo/blob/master/documentation-api/introduction.md et https://github.com/AntoineAugusti/diplo/blob/master/documentation-api/toc.md.

Fais-le et ping moi quand ce sera fait.

**Comment by AntoineAugusti** [comment]
@etiennebatise Ne traîne pas pour cette tâche, @NathanMalo utilise la documentation de l'API en ligne pour coder le client et on se base sur ça pour coder l'API côté serveur

**Comment by etiennebatise** [comment]
@NathanMalo @jeanclaudeb @manonansart 
J'ai légèrement modifié les noms des champs du JSON renvoyé par l'API.

C'est là  https://github.com/AntoineAugusti/diplo/blob/master/documentation-api/endpoints/parties/GET_parties_id_armees.md#description-de-la-r%C3%A9ponse

**Comment by AntoineAugusti** [comment]
@manonansart @NathanMalo @jeanclaudeb Done in https://github.com/AntoineAugusti/diplo/commit/62111efaec9554282fc5a27851ded303a260d725

La liste des endpoints disponibles est toujours dans https://github.com/AntoineAugusti/diplo/issues/3
