### ISSUE TITLE
Nombre de joueurs inscrits

### ISSUE THREAD

**Issue by nat93-dev** [AntoineAugusti/diplo#11]
Une exception est soulevée du type partie_pleine lors de l'inscription du 5ème joueurs à une partie, alors qu'il faut 5 joueurs.

**Comment by nat93-dev** [comment]
ping @AntoineAugusti @ThibaudDauce @etiennebatise

**Comment by AntoineAugusti** [comment]
Je regarde ça dans l'après-midi

**Comment by AntoineAugusti** [comment]
Le comportement est bien le bon. Je pense que tu as loupé un point important de la documentation sur la méthode [POST parties/:id/rejoindre](https://developers.diplo-lejeu.fr/diplo/1.0/endpoints/parties/POST_parties_id_rejoindre). La description de `nb_joueurs_inscrits` indique bien "Le nombre de joueurs inscrits dans la partie, **avant d'avoir fait la demande de rejoindre la partie**"

Par défaut quand tu réinitialises la BD il y a 3 joueurs d'inscrits dans la partie 1. Tu peux demander à rejoindre 2 fois avant que la partie soit pleine. Pour la dernière requête le champ `nb_joueurs_inscrits` sera donc à 4, puisqu'il y avait 4 joueurs dans la partie **avant** de demander à rejoindre la partie. Le fait qu'un 5ème joueur rejoigne la partie entraine l'impossibilité de rejoindre la partie ensuite.

Je te laisse fermer l'issue une fois que tout ceci est bien clair et que le fonctionnement est bien ce que j'ai expliqué.

**Comment by nat93-dev** [comment]
My bad merci :)
