### ISSUE TITLE
Erreur 500 sur le endpoint des phases

### ISSUE THREAD

**Issue by nat93-dev** [AntoineAugusti/diplo#12]
Quand on appelle le endpoint des phases, erreur 500  : 
015/04/27 12:43:00 [error] 25206#0: *2561 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to a member function diffInSeconds() on a non-object in /var/www/api/app/Http/Controllers/PartiesController.php on line 61" while reading response header from upstream, client: 108.162.229.78, server: api.diplo-lejeu.fr, request: "GET /parties/1/phase HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "api.diplo-lejeu.fr"

**Comment by nat93-dev** [comment]
ping @AntoineAugusti @ThibaudDauce @etiennebatise

**Comment by AntoineAugusti** [comment]
Fixé. J'ai mis à jour le script de redéploiement sur le serveur qui se trouve dans `/var/www`.

``` bash
git clone https://github.com/AntoineAugusti/diplo.git tmp
mv tmp/application/serveur apiNew
cp api/.env apiNew/.env
cd apiNew
composer install
php artisan clear-compiled
# Ligne ajoutée
php artisan migrate:reset --force
php artisan migrate --force
php artisan db:seed --force
cd ..
rm -rf api/
rm -rf tmp/
mv apiNew api
chown -R www-data:www-data /var/www/api
```

Ferme dans quelques heures si le problème ne se reproduit pas.

**Comment by nat93-dev** [comment]
J'ai maintenant une 405, ce qui est normal :)
