### ISSUE TITLE
Endpoint ordre

### ISSUE THREAD

**Issue by nat93-dev** [AntoineAugusti/diplo#13]
L'URI de l'endpoint Ordres est juste Ordre dans la doc. Ce ne serait pas plutôt parties/partieID/ordre afin de savoir sur quelle partie on envoit l'ordre ?

**Comment by nat93-dev** [comment]
ping @AntoineAugusti

**Comment by AntoineAugusti** [comment]
@ThibaudDauce Si tu peux lui répondre et trancher pour cette question.

**Comment by ThibaudDauce** [comment]
L'ID d'une armée est unique à travers les parties c'est pour ça qu'on a pas besoin de spécifier la partie en cours.

**Comment by ThibaudDauce** [comment]
Tout est bon @NathanMalo ?

**Comment by nat93-dev** [comment]
Okay ça marche merci @ThibaudDauce je modifierai mon code cette semaine.
