### ISSUE TITLE
Associer une couleur à un joueur

### ISSUE THREAD

**Issue by jeanclaudeb** [AntoineAugusti/diplo#14]
Il faudrait associer une couleur à un joueur pour afficher les cases qu'il contrôle de cette couleur. Il faudrait donc un int compris entre 41 et 46 (bornes incluses). Ce sont des couleurs de bases supportées en bash.

Thanks in advance :kissing_closed_eyes:

**Comment by AntoineAugusti** [comment]
@jeanclaudeb Même chose que l'autre question. Propre à l'UI, peut être généré à partir de l'ID du joueur aussi.

**Comment by jeanclaudeb** [comment]
Copy that!
