### ISSUE TITLE
Rédaction rapport final

### ISSUE THREAD

**Issue by AntoineAugusti** [AntoineAugusti/diplo#15]
J'ai commencé à remplir ce qu'on doit faire pour le rapport final dans le dossier `rapports/final`. Voici les parties qu'il faut réaliser (déjà créées dans des fichiers LaTeX, plus ou moins vides).
- [x] Spécifications mises à jour @antoineaugusti
- Conception mise à jour
  - [x] Client @manonansart
  - [x] Serveur @etiennebatise 
- Choix techniques
  - [x] Client @NathanMalo
  - [x] Serveur @antoineaugusti
- Problèmes rencontrés et solutions apportées
  - [x] Client @jeanclaudeb et @NathanMalo
  - [x] Serveur @antoineaugusti et @ThibaudDauce 
- Améliorations possibles
  - [x] Client @manonansart 
  - [x] Serveur @ThibaudDauce 
- Répartition des tâches
  - [x] Client @NathanMalo
  - [x] Serveur @etiennebatise 

À livrer plus tard :
- Code source
- Présentation
- Vidéo de démonstration

Commentaires, questions, avancement ici ;)

**Comment by AntoineAugusti** [comment]
@jeanclaudeb @NathanMalo @manonansart Je vous laisse voir comment vous voulez écrire les parties concernant le client.

**Comment by AntoineAugusti** [comment]
Up. Pour rappel la présentation est le mardi de la semaine de la rentrée.

**Comment by AntoineAugusti** [comment]
@ThibaudDauce Pour l'amélioration des performances tu pourrais parler de la séparation physique des services. Actuellement on utilise une machine pour la BDD, le serveur web et la queue worker. On pourrait gagner des performances en séparant tout ça ;)

**Comment by antoine** [comment]
le @antoine que vous utilisez n'est pas celui que vous croyez

**Comment by AntoineAugusti** [comment]
@antoine Désolé pour la notification intempestive ! Github ne propose pas d'autocompléter son propre username quand on écrit. J'ai donc été fainéant et j'ai écrit seulement mon prénom, sans penser aux conséquences. C'est rectifié.

**Comment by nat93-dev** [comment]
@jeanclaudeb Pour la partie problèmes rencontrés tu pourrais parler de l'affichage de la carte ? Je pensais rajouter en perso le coup du user agent dans la requête https qui faisait chier.

**Comment by AntoineAugusti** [comment]
@ThibaudDauce Pense à cocher ta partie quand tu auras terminé. Il me semble que tu as pas mal avancé.

**Comment by AntoineAugusti** [comment]
@ThibaudDauce Si tu peux parler dans les améliorations possibles côté serveur de proposer un outil pour assigner une partie quand on cherche à en rejoindre une :) À mentionner dans la soutenance aussi

**Comment by etiennebatise** [comment]
Je viens de finir la mise à jour du DC niveau serveur. Travail long niveau "mise en page" à cause du grand nombre de figures (mise à l'echelle, découpage du DC généré). 

Bref si vous avez des remarques avant de valider, je suis tout ouïe.

**Comment by ThibaudDauce** [comment]
@AntoineAugusti Fait dans https://github.com/AntoineAugusti/diplo/commit/adf869045f114ff645cf365a17ec69767399c627 et https://github.com/AntoineAugusti/diplo/commit/2c91b0daa4165fc1c8c9b2229672b4e646e8ff74

**Comment by etiennebatise** [comment]
@jeanclaudeb @manonansart @NathanMalo J'ai mis le skin flat sur tout les .plantuml que je pouvais mail il manque le _diagramme de packages_ côté client. 
J'ai automatisé la génération des png du coup ils sont maintenant générés dans le dossier `diagrammes` et la commande est dans le `makefile` avec plantuml .

**Comment by etiennebatise** [comment]
@AntoineAugusti  @ThibaudDauce  
Répartition des tâches côté serveur fait dans https://github.com/AntoineAugusti/diplo/commit/eafc460730c0569aca238cd9a8149cd62859d17d

**Comment by AntoineAugusti** [comment]
@EtienneBatise Je vais modifier quelques trucs, c'est très bien

**Comment by AntoineAugusti** [comment]
@jeanclaudeb @NathanMalo La partie problèmes rencontrés c'est bon pour le rapport ?

**Comment by nat93-dev** [comment]
@jeanclaudeb is eating and will answer later :)

**Comment by AntoineAugusti** [comment]
@NathanMalo Sacrée secrétaire ! @jeanclaudeb
