### ISSUE TITLE
Tester carte en milieu de jeu

### ISSUE THREAD

**Issue by AntoineAugusti** [AntoineAugusti/diplo#16]
Tu peux modifier la méthode `handle` de `Diplo\Commands\PartiePhaseSwitcherHandler` et rajouter quelque chose du style, pour tester en local avec un driver de queue `sync` :

``` php
if ($partie->tour_courant == 3 AND $partie->phase == Partie::COMBAT)
    return;
```

Pour forcer à sortir et tester dans un état. J'ai fixé le schéma des tables dans https://github.com/AntoineAugusti/diplo/commit/1c81ac201487ddc91f052f460b54e6eb5a64fc78

Tu peux inspecter la BD ensuite pour vérifier que la logique est bien implémentée. L'endpoint permettant de voir beaucoup de chose serait [GET parties/:id/carte](https://developers.diplo-lejeu.fr/diplo/1.0/endpoints/parties/GET_parties_id_carte)

**Comment by ThibaudDauce** [comment]
J'ai fait une méthode /testCreerPartie qui permet de lancer la création d'une partie, je check ensuite dans la base sqlite voir que tout est bien créé.

C'est très long...
