### ISSUE TITLE
Cases de la carte

### ISSUE THREAD

**Issue by ThibaudDauce** [AntoineAugusti/diplo#17]
Dans `Partie.php` j'ai :

``` php
<?php
    /**
     * Récupère la carte de la partie.
     *
     * @return Carte
     */
    public function getCarte()
    {
        return $this->carte;
    }
```

Lorsque je mets `return $this->carte->load('cases');` j'ai une erreur étrange qui vient d'`$append` dans `CaseClass.php`, est-ce que tu as une idée @AntoineAugusti ?

**Comment by AntoineAugusti** [comment]
Tu as une stack trace ? Je n'utilise pas souvent loads

Antoine Augusti
www.antoine-augusti.fr

**Comment by AntoineAugusti** [comment]
J'ai déjà bien avancé sur le problème dans https://github.com/AntoineAugusti/diplo/commit/32ec229db82014f4fa1cf1f53150e934b3e42a83 mais j'ai toujours un problème avec `$appends` dès que je demande les ID des cases voisines avec la clé `id_cases_voisines`. Ça fait une boucle infinie immédiatement et je n'ai pas encore trouvé la source.

Je me demande si ça retombe pas sur une case, ça cherche à charger les `$appends` et du coup ça boucle sur les voisins, des voisins, des voisins... Mais j'ai un doute sur cette théorie car on demande un `lists('id')` et donc ça ne devrait jamais charger les modèles.

Sinon il faudra désactiver les `$appends` sur les classes et rajouter automatiquement les informations manquants pour chaque case, ou un truc du style.

**Comment by ThibaudDauce** [comment]
Fix via https://github.com/AntoineAugusti/diplo/commit/22cc3f9181d9a8f0fa44bbf5b99cf7db21516571
