### ISSUE TITLE
Évènements fin de phase

### ISSUE THREAD

**Issue by ThibaudDauce** [AntoineAugusti/diplo#18]
Je trouve les noms  `PartieChangeDePhase` et  `PartieChangeDeTour` pas très parlant.

@AntoineAugusti Est-ce que tu peux rajouter un comentaire sur les classes disant bien quel type de phase l'on quitte et dans quel type de phase on entre ?

**Comment by AntoineAugusti** [comment]
Je vais faire ça. Pour t'aider, c'est quand le changement vient d'être effectué. Par exemple, j'étais en phase de négociation, celle-ci vient de se terminer et donc je passe en phase de combat, je vais lancer l'événement `PartieChangeDePhase` avec en paramètre la partie concernée et la nouvelle phase, c'est-à-dire `Partie::COMBAT` ici

**Comment by AntoineAugusti** [comment]
Closed in https://github.com/AntoineAugusti/diplo/commit/20a8817f695101a21715f34a8e806d1918ed11cc. @ThibaudDauce si ce n'est pas suffisant indique-moi ce qui n'est pas clair et où tu veux que je rajoute des choses.
