### ISSUE TITLE
Vérification de la procédure d'exécution des ordres

### ISSUE THREAD

**Issue by ThibaudDauce** [AntoineAugusti/diplo#19]
@AntoineAugusti @etiennebatise 

J'aimerais bien de l'aide pour que quelqu'un relise le scénario lors de l'exécution des ordres.
Tout est détaillé dans mon commit https://github.com/AntoineAugusti/diplo/commit/d5d697ed267023b397516b0805ec3cc261a71746, il suffit de suivre les points.

Normalement je l'ai déjà fait mais j'ai peut être oublié des trucs au niveau des règles ou j'ai peut être fait des erreurs au niveau du PHP (c'est difficilement testable ces machins là :( normalement l'IDE ne râle pas trop donc ça devrait aller niveau syntaxe)

Des bisous !

**Comment by AntoineAugusti** [comment]
J'ai relu attentivement et je ne pense pas avoir vu d'erreurs de logique métier. J'ai rajouté des commentaires et j'ai utilisé l'attribut `est_occupee` pour une case également. https://github.com/AntoineAugusti/diplo/commit/9c103d42bafbde4e6200582278e170aabf1183d9

**Comment by AntoineAugusti** [comment]
En attente de retour d'éventuels bugs de la team frontend @manonansart @NathanMalo @jeanclaudeb
