### ISSUE TITLE
Schéma DB messages de groupe

### ISSUE THREAD

**Issue by AntoineAugusti** [AntoineAugusti/diplo#2]
Yop, je me pose la question sur la modélisation en BD relationnelle des messages entre plusieurs utilisateurs. @etiennebatise @ThibaudDauce, une idée de modélisation ?

**Comment by ThibaudDauce** [comment]
Une conversation à plusieurs personnes et un message appartient à une conversation ?

**Comment by AntoineAugusti** [comment]
@ThibaudDauce Ok pour ça, mais comment avoir "plusieurs personnes" pour une conversation ? Tu ne peux pas stocker un tableau d'identifiants de joueurs et séparer les identifiants de joueurs dans une colonne (exemple : `1,5,7`) n'est pas très adapté pour les requêtes.

**Comment by ThibaudDauce** [comment]
Bah c'est une many to many classique avec une table pivot ?

**Comment by AntoineAugusti** [comment]
Ah yep :) La fatigue :beer:

**Comment by ThibaudDauce** [comment]
Tu me fais peur là Antoine :-) 
Parler d'ID séparés par des virgules ça me fait penser à Quantic dans les premières années :-P

**Comment by AntoineAugusti** [comment]
:mask:
