### ISSUE TITLE
Gérer l'appartenance d'une case à un joueur

### ISSUE THREAD

**Issue by AntoineAugusti** [AntoineAugusti/diplo#20]
Quand un joueur a une armée sur une case, il en prend possession. S'il déplace son armée sur une autre case, la case doit toujours être possédée par le joueur, jusqu'à ce qu'une armée ennemie vienne sur cette case.

La méthode à implémenter au final `Joueur@getCasesControleesAttribute()` mais il y a des choses à revoir dans les cases et la gestion des ordres

**Comment by ThibaudDauce** [comment]
Fait. https://github.com/AntoineAugusti/diplo/commit/e352bd22ff05281c8adeb088df9d763cf508b925 https://github.com/AntoineAugusti/diplo/commit/b1df63bbc182a26fcc796e9db2ee5c554d1fb9eb
