### ISSUE TITLE
Erreur 500 sur POST conversations

### ISSUE THREAD

**Issue by nat93-dev** [AntoineAugusti/diplo#22]
Lorsque je requête pour créer une conversation j'essuie une erreur 500, mon JSON est bien formé, 
voici les logs du serveur : 
2015/05/04 18:28:57 [error] 1185#0: *800 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'Exception' with message 'Bugsnag Error: Invalid API key' in /var/www/api/vendor/bugsnag/bugsnag/src/Bugsnag/Client.php:17
Stack trace:
#0 /var/www/api/vendor/bugsnag/bugsnag-laravel/src/Bugsnag/BugsnagLaravel/BugsnagLaravelServiceProvider.php(54): Bugsnag_Client->__construct(NULL)
#1 /var/www/api/vendor/laravel/framework/src/Illuminate/Container/Container.php(773): Bugsnag\BugsnagLaravel\BugsnagLaravelServiceProvider->Bugsnag\BugsnagLaravel{closure}(Object(Illuminate\Foundation\Application), Array)
#2 /var/www/api/vendor/laravel/framework/src/Illuminate/Container/Container.php(656): Illuminate\Container\Container->build(Object(Closure), Array)
#3 /var/www/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(644): Illuminate\Container\Container->make('bugsnag', Array)
#4 /var/www/api/vendor/laravel/framework/src/Illuminate/Container/Container.php(1231): Illuminate\Foundation\Application->make('bugsnag')
#5 /var/www/api/vendor/bugsnag/bug...

PHP message: PHP Fatal error:  Uncaught exception 'Exception' with message 'Bugsnag Error: Invalid API key' in /var/www/api/vendor/bugsnag/bugsnag/src/Bugsnag/Client.php:17
Stack trace:
#0 /var/www/api/vendor/bugsnag/bugsnag-laravel/src/Bugsnag/BugsnagLaravel/BugsnagLaravelServiceProvider.php(54): Bugsnag_Client->__construct(NULL)
#1 /var/www/api/vendor/laravel/framework/src/Illuminate/Container/Container.php(773): Bugsnag\BugsnagLaravel\BugsnagLaravelServiceProvider->Bugsnag\BugsnagLaravel{closure}(Object(Illuminate\Foundation\Application), Array)
#2 /var/www/api/vendor/laravel/framework/src/Illuminate/Container/Container.php(656): Illuminate\Container\Container->build(Object(Closure), Array)
#3 /var/www/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(644): Illuminate\Container\Container->make('bugsnag', Array)
#4 /var/www/api/vendor/laravel/framework/src/Illuminate/Container/Container.php(1231): Illuminate\Foundation\

**Comment by nat93-dev** [comment]
ping @AntoineAugusti @ThibaudDauce @etiennebatise

**Comment by AntoineAugusti** [comment]
OK je prends. C'est un problème avec l'API de Bugsnag à première vue.

**Comment by AntoineAugusti** [comment]
Je peux avoir le JSON que tu as envoyé également stp ?

**Comment by nat93-dev** [comment]
{"joueurs" :[4]}

**Comment by AntoineAugusti** [comment]
I'm on it @NathanMalo

**Comment by nat93-dev** [comment]
Merci :heart:

**Comment by AntoineAugusti** [comment]
J'ai refactoré, ce n'est pas ça qui posait problème mais c'est fait dans https://github.com/AntoineAugusti/diplo/commit/b99cd7a1f60a0232cb3fac9b784fa78fc2870d58 Je te laisse réessayer et fermer l'issue.

Je viens de taper avec `curl -H "Content-Type: application/json" -X POST -d '{"joueurs": [4]}' https://api.diplo-lejeu.fr/conversations` et tout va bien

**Comment by nat93-dev** [comment]
C'est bon j'ai eu une erreur 400, une conversation ne peut-être crée qu'entre deux joueurs ou plus. Champion ! Merci !
