### ISSUE TITLE
GET conversations

### ISSUE THREAD

**Issue by nat93-dev** [AntoineAugusti/diplo#23]
Dans l'API, on a l'endpoint conversations qui permet de retrouver une conversation par l'id, mais n'est-ce pas une brèche de sécurité ? Un joueur pourrait lire les conversations de concurrents et ainsi connaître leurs tactiques ?
Ping @AntoineAugusti @ThibaudDauce @etiennebatise

**Comment by AntoineAugusti** [comment]
La brèche de sécurité est bien avant ça. Tu peux donner des ordres à
d'autres armées si jamais tu fais la requête qui va bien.

Le seul moyen de sécuriser ça c'est d'avoir des comptes utilisateurs avec
identifiant et mot de passe ainsi que de l'OAuth 2. Mais ce sont des temps
de développement bien plus longs. @ThibaudDauce

**Comment by ThibaudDauce** [comment]
Vu qu'il n'y a pas d'authentification sur l'application, c'est sûr que tout est possible ^^

**Comment by nat93-dev** [comment]
Pauchet le verra même pas si ça se trouve !
