### ISSUE TITLE
Reflexion autour du langage PHP : return; ou return null;

### ISSUE THREAD

**Issue by ThibaudDauce** [AntoineAugusti/diplo#24]
Information à destination d'@AntoineAugusti et d'@etiennebatise (mais ça peut aussi intéresser les autres : @NathanMalo @jeanclaudeb @manonansart)

Personnellement je trouve que l'utilisation de `return;` à la place de `return null;` c'est très très moche. Même si ça fait parti des conventions de code de Symfony.

Du coup j'aimerais que vous utilisiez la ligne `php-cs-fixer fix app --fixers=-empty_return` pour corriger le code afin que les `return;` ne réapparaissent pas.

Pour l'explication, notre documentation définit que nous retournons dans certains cas la valeur `null`, valeur très particulière en PHP (comme dans beaucoup d'autres langages). Qui est d'ailleurs une des grandes failles des languages actuels (les fameux `NullPointerException` font des ravages dans les codes source). Les langages un peu plus stricts (et plus intelligents) utilise des types conteneurs (je ne connais pas le vrai terme) du genre Option / Some en Scala ou Maybe en Haskell par exemple.

Cette paranthèse fermée, l'utilisation du simple `return;` est basé sur le fait que PHP renvoie par défaut la valeur `null` des fonctions. Or il n'est pas garantit que cette pratique perdure dans le temps, il y a beaucoup plus de chance que PHP change de comportement plutôt que `return null;` change de valeur. La seconde solution est donc plus solide et résistera mieux aux évolutions du langage. En plus d'être plus lisible (pas besoin de connaître la valeur par défaut de PHP pour comprendre le code).

Voilà :)

**Comment by AntoineAugusti** [comment]
Tout à fait d'accord. Je déteste cette convention également et je trouve ça très crétin de retourner par défaut `null` quand une méthode ne doit rien retourner. Ça a déjà été débattu plusieurs fois sur le langage, c'est quelque chose qui fait débat.

Merci d'avoir regardé la documentation de PHP CS Fixer pour trouver comment changer ce comportement :wink:
