### ISSUE TITLE
Génération PlantUML depuis source PHP

### ISSUE THREAD

**Issue by AntoineAugusti** [AntoineAugusti/diplo#25]
Je viens de trouver un super outil permettant de générer notre PlantUML directement depuis l'application : https://github.com/davidfuhr/php-plantumlwriter

Voilà ce qu'il faut faire à peu près : 

``` bash
composer global require davidfuhr/php-plantumlwriter
# Pour le package des armées
php /Users/Augusti/.composer/vendor/davidfuhr/php-plantumlwriter/bin/php-plantumlwriter write /Users/Augusti/Desktop/INSA/diplo/application/serveur/app/Armees > armees.puml
```

Apparemment on peut faire tout le dossier `app` d'un coup, mais j'obtiens une erreur... Si @ThibaudDauce tu as une idée. Peut-être que c'est le nom de la classe `CaseClass` qui ne lui va pas.

Ça a l'air excellent. Étienne, peux-tu écrire un petit script Bash pour générer tous les fichiers qui vont bien, module par module et de manière générale aussi ?

**Comment by ThibaudDauce** [comment]
Commande pour générer tout le projet :

``` bash
find app -name '*.php' -print | xargs php-plantumlwriter write > projet.plantuml
```

**Comment by ThibaudDauce** [comment]
Si il y a une erreur c'est normal c'est route.php je pense qui emet un warning

**Comment by AntoineAugusti** [comment]
En faisant ça tu as pas des problèmes avec les start et les end tag de
PlantUML ?

**Comment by ThibaudDauce** [comment]
Absolument pas, c'est bien géré http://p-w.fr/1deqj

**Comment by AntoineAugusti** [comment]
Je m'en vais de ce pas imprimer ce magnifique diagramme.

**Comment by ThibaudDauce** [comment]
J'adore l'URL de PlantUML :D
Il y a moyen de faire des de nouvelles couches pour les Exception ça serait mieux je pense...

**Comment by AntoineAugusti** [comment]
Yep, tu peux faire une exception parente par module je pense. Tu peux le
faire ?

**Comment by ThibaudDauce** [comment]
Demain :)

**Comment by AntoineAugusti** [comment]
@etiennebatise Le skin à utiliser pour le diagramme PlantUML http://pastebin.com/BjBSS3nA
