### ISSUE TITLE
Refactor des exceptions

### ISSUE THREAD

**Issue by AntoineAugusti** [AntoineAugusti/diplo#26]
- [x] Créer une exception parente par module et faire hériter les autres exceptions de celle-ci (armées, cases, conversations, joueurs, ordres, parties) (done in https://github.com/AntoineAugusti/diplo/commit/354f1c0bc9125f816259520f4a2c35557f6c730f)
- [x] Refactor de la classe `Diplo\Exceptions\Handler` (done in https://github.com/AntoineAugusti/diplo/commit/92bd25f46a5397726e0235a1f8366c63584f1fab)

**Comment by ThibaudDauce** [comment]
J'ai pas mal réfléchi à comment faire ça, j'ai mis en place une solution... Je ne sais pas ce que ça vaut...

**Comment by AntoineAugusti** [comment]
J'ai lu rapidement ton commit, je lirai plus attentivement dans
l'après-midi mais ça a l'air très propre.

Cette API est magnifiquement conçue quand même ! Pattern middleware, niquel.

**Comment by AntoineAugusti** [comment]
J'ai amélioré la documentation à coup de PHP-CS-Fixer dans https://github.com/AntoineAugusti/diplo/commit/10dbf6ea59a291dad65850667035727d804b477d. Sinon l'implémentation est très bien !

Je clos.

**Comment by ThibaudDauce** [comment]
J'aime pas la définition des tableaux vides avec `array()` je trouve ça tellement vieux jeu, c'est tellement plus beau `[]`

**Comment by AntoineAugusti** [comment]
Tu peux changer si tu veux, je suis d'accord avec toi. J'avais fait ça
uniquement parce que la coloration syntaxique de Sublime Text bugguait avec
cette syntaxe, qui est pourtant valide.

**Comment by AntoineAugusti** [comment]
@ThibaudDauce Done in https://github.com/AntoineAugusti/diplo/commit/ca1d87b1036453aabdd74bb5b0cbfdbf08e2e443
