### ISSUE TITLE
Préparation soutenance

### ISSUE THREAD

**Issue by AntoineAugusti** [AntoineAugusti/diplo#27]
- [x] Spécifications du projet @antoineaugusti
- Choix techniques
  - [x] Serveur @antoineaugusti
  - [x] Client @nathanmalo
- Problèmes rencontrés et solutions apportées
  - [x] Client @jeanclaudeb
  - [x] Serveur @etiennebatise  
- Améliorations possibles
  - [x] Client @manonansart 
  - [x] Serveur @ThibaudDauce

Commentaires, questions, avancement ici ;)

**Comment by AntoineAugusti** [comment]
@NathanMalo @jeanclaudeb @manonansart Oubliez pas de voir comment vous écrivez vos parties :)

**Comment by nat93-dev** [comment]
@manonansart @jeanclaudeb J'ai mis à jour nos rôles, si ça vous va :)

**Comment by AntoineAugusti** [comment]
@NathanMalo @jeanclaudeb @manonansart J'ai dégagé l'image de la conception client parce que c'est trop gros. (https://diplo-lejeu.fr/images/packages-client.png ou https://diplo-lejeu.fr/images/client.png)

Je pense que de toute façon ce sera tendu de faire ça en 10mn !

**Comment by nat93-dev** [comment]
OK ça passera :)
