### ISSUE TITLE
Endpoint rejoindre

### ISSUE THREAD

**Issue by nat93-dev** [AntoineAugusti/diplo#28]
Erreur 500, error.log :
2015/05/08 20:08:11 [error] 7088#0: *153 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to a member function getOrdre() on a non-object in /var/www/api/app/Handlers/Events/ExecuterOrdres.php on line 54" while reading response header from upstream, client: 173.245.49.228, server: api.diplo-lejeu.fr, request: "POST /parties/1/rejoindre HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "api.diplo-lejeu.fr"

**Comment by nat93-dev** [comment]
ping @AntoineAugusti @ThibaudDauce

**Comment by AntoineAugusti** [comment]
@NathanMalo Il s'est passé quoi avant ? Des ordres ont été donnés ? Donne les requêtes exécutées avant

**Comment by nat93-dev** [comment]
On a rejoint une première fois, qui fut un succès.

**Comment by ThibaudDauce** [comment]
Je suis dessus.

**Comment by AntoineAugusti** [comment]
@ThibaudDauce Go IRC
