### ISSUE TITLE
Modification taille de carte

### ISSUE THREAD

**Issue by nat93-dev** [AntoineAugusti/diplo#29]
Hi,
Actuellement le temps entre l'arrivée de tous les joueurs et le lancement de la partie est plutôt, plusieurs secondes, voire dizaine de secondes.

Y a t-il moyen de raccourcir ce temps ?

Tcho !

**Comment by AntoineAugusti** [comment]
C'est la création de la carte qui est longue dès qu'une partie est rejointe par la toute dernière personne. Il y a 225 cases à créer en BD, des armées à placer et les liaisons à assurer avec les joueurs. Ça fait beaucoup de requêtes, surtout qu'il y a des allers-retours avec la queue.

Je pense qu'on peut grappiller quelques secondes, mais pas forcément facilement. Est-ce vraiment un problème ? La partie ne sera pas marquée comme "démarrée" tant que ceci n'aura pas été réellement bien terminé.

@ThibaudDauce

**Comment by nat93-dev** [comment]
Ok je comprends, d'ailleurs @jeanclaudeb préconise 15 colonnes et 10 lignes, soit 150 cases max sinon ça rentre pas dans le terminal ou du moins mal.
C'est possible de modifier ?

**Comment by AntoineAugusti** [comment]
Peut-être plus sur un carré de 10x10 alors. @ThibaudDauce, qu'en penses-tu ?

**Comment by nat93-dev** [comment]
10 x10 convient à @jeanclaudeb :)

**Comment by AntoineAugusti** [comment]
Carte modifiée en 10x10 dans https://github.com/AntoineAugusti/diplo/commit/964b0f12611492a0e57c13447df271812b673de0. J'attends votre retour @NathanMalo @jeanclaudeb

**Comment by nat93-dev** [comment]
Super merci, on te redit ;)

**Comment by nat93-dev** [comment]
Much better, c'est plus rapide merci :)
