### ISSUE TITLE
endpoint get_id_armees

### ISSUE THREAD

**Issue by nat93-dev** [AntoineAugusti/diplo#30]
Lors de l'appel du endpoint parties/1/armees on a un resultat de 300 armées au lieu des 4 \* 5 armées affichées correctement sur la case.

Fix ? :)

JSON : 

{"armees":[{"id":1,"id_joueur":1,"id_case":1},{"id":2,"id_joueur":1,"id_case":2},{"id":3,"id_joueur":1,"id_case":11},{"id":4,"id_joueur":1,"id_case":12},{"id":21,"id_joueur":1,"id_case":101},{"id":22,"id_joueur":1,"id_case":102},{"id":23,"id_joueur":1,"id_case":111},{"id":24,"id_joueur":1,"id_case":112},{"id":41,"id_joueur":1,"id_case":201},{"id":42,"id_joueur":1,"id_case":202},{"id":43,"id_joueur":1,"id_case":211},{"id":44,"id_joueur":1,"id_case":212},{"id":61,"id_joueur":1,"id_case":301},{"id":62,"id_joueur":1,"id_case":302},{"id":63,"id_joueur":1,"id_case":311},{"id":64,"id_joueur":1,"id_case":312},{"id":81,"id_joueur":1,"id_case":401},{"id":82,"id_joueur":1,"id_case":402},{"id":83,"id_joueur":1,"id_case":411},{"id":84,"id_joueur":1,"id_case":412},{"id":101,"id_joueur":1,"id_case":501},{"id":102,"id_joueur":1,"id_case":502},{"id":103,"id_joueur":1,"id_case":511},{"id":104,"id_joueur":1,"id_case":512},{"id":121,"id_joueur":1,"id_case":601},{"id":122,"id_joueur":1,"id_case":602},{"id":123,"id_joueur":1,"id_case":611},{"id":124,"id_joueur":1,"id_case":612},{"id":141,"id_joueur":1,"id_case":701},{"id":142,"id_joueur":1,"id_case":702},{"id":143,"id_joueur":1,"id_case":711},{"id":144,"id_joueur":1,"id_case":712},{"id":161,"id_joueur":1,"id_case":801},{"id":162,"id_joueur":1,"id_case":802},{"id":163,"id_joueur":1,"id_case":811},{"id":164,"id_joueur":1,"id_case":812},{"id":181,"id_joueur":1,"id_case":901},{"id":182,"id_joueur":1,"id_case":902},{"id":183,"id_joueur":1,"id_case":911},{"id":184,"id_joueur":1,"id_case":912},{"id":201,"id_joueur":1,"id_case":1001},{"id":202,"id_joueur":1,"id_case":1002},{"id":203,"id_joueur":1,"id_case":1011},{"id":204,"id_joueur":1,"id_case":1012},{"id":221,"id_joueur":1,"id_case":1101},{"id":222,"id_joueur":1,"id_case":1102},{"id":223,"id_joueur":1,"id_case":1111},{"id":224,"id_joueur":1,"id_case":1112},{"id":241,"id_joueur":1,"id_case":1201},{"id":242,"id_joueur":1,"id_case":1202},{"id":243,"id_joueur":1,"id_case":1211},{"id":244,"id_joueur":1,"id_case":1212},{"id":261,"id_joueur":1,"id_case":1301},{"id":262,"id_joueur":1,"id_case":1302},{"id":263,"id_joueur":1,"id_case":1311},{"id":264,"id_joueur":1,"id_case":1312},{"id":281,"id_joueur":1,"id_case":1401},{"id":282,"id_joueur":1,"id_case":1402},{"id":283,"id_joueur":1,"id_case":1411},{"id":284,"id_joueur":1,"id_case":1412},{"id":5,"id_joueur":2,"id_case":9},{"id":6,"id_joueur":2,"id_case":10},{"id":7,"id_joueur":2,"id_case":19},{"id":8,"id_joueur":2,"id_case":20},{"id":25,"id_joueur":2,"id_case":109},{"id":26,"id_joueur":2,"id_case":110},{"id":27,"id_joueur":2,"id_case":119},{"id":28,"id_joueur":2,"id_case":120},{"id":45,"id_joueur":2,"id_case":209},{"id":46,"id_joueur":2,"id_case":210},{"id":47,"id_joueur":2,"id_case":219},{"id":48,"id_joueur":2,"id_case":220},{"id":65,"id_joueur":2,"id_case":309},{"id":66,"id_joueur":2,"id_case":310},{"id":67,"id_joueur":2,"id_case":319},{"id":68,"id_joueur":2,"id_case":320},{"id":85,"id_joueur":2,"id_case":409},{"id":86,"id_joueur":2,"id_case":410},{"id":87,"id_joueur":2,"id_case":419},{"id":88,"id_joueur":2,"id_case":420},{"id":105,"id_joueur":2,"id_case":509},{"id":106,"id_joueur":2,"id_case":510},{"id":107,"id_joueur":2,"id_case":519},{"id":108,"id_joueur":2,"id_case":520},{"id":125,"id_joueur":2,"id_case":609},{"id":126,"id_joueur":2,"id_case":610},{"id":127,"id_joueur":2,"id_case":619},{"id":128,"id_joueur":2,"id_case":620},{"id":145,"id_joueur":2,"id_case":709},{"id":146,"id_joueur":2,"id_case":710},{"id":147,"id_joueur":2,"id_case":719},{"id":148,"id_joueur":2,"id_case":720},{"id":165,"id_joueur":2,"id_case":809},{"id":166,"id_joueur":2,"id_case":810},{"id":167,"id_joueur":2,"id_case":819},{"id":168,"id_joueur":2,"id_case":820},{"id":185,"id_joueur":2,"id_case":909},{"id":186,"id_joueur":2,"id_case":910},{"id":187,"id_joueur":2,"id_case":919},{"id":188,"id_joueur":2,"id_case":920},{"id":205,"id_joueur":2,"id_case":1009},{"id":206,"id_joueur":2,"id_case":1010},{"id":207,"id_joueur":2,"id_case":1019},{"id":208,"id_joueur":2,"id_case":1020},{"id":225,"id_joueur":2,"id_case":1109},{"id":226,"id_joueur":2,"id_case":1110},{"id":227,"id_joueur":2,"id_case":1119},{"id":228,"id_joueur":2,"id_case":1120},{"id":245,"id_joueur":2,"id_case":1209},{"id":246,"id_joueur":2,"id_case":1210},{"id":247,"id_joueur":2,"id_case":1219},{"id":248,"id_joueur":2,"id_case":1220},{"id":265,"id_joueur":2,"id_case":1309},{"id":266,"id_joueur":2,"id_case":1310},{"id":267,"id_joueur":2,"id_case":1319},{"id":268,"id_joueur":2,"id_case":1320},{"id":285,"id_joueur":2,"id_case":1409},{"id":286,"id_joueur":2,"id_case":1410},{"id":287,"id_joueur":2,"id_case":1419},{"id":288,"id_joueur":2,"id_case":1420},{"id":9,"id_joueur":3,"id_case":45},{"id":10,"id_joueur":3,"id_case":46},{"id":11,"id_joueur":3,"id_case":55},{"id":12,"id_joueur":3,"id_case":56},{"id":29,"id_joueur":3,"id_case":145},{"id":30,"id_joueur":3,"id_case":146},{"id":31,"id_joueur":3,"id_case":155},{"id":32,"id_joueur":3,"id_case":156},{"id":49,"id_joueur":3,"id_case":245},{"id":50,"id_joueur":3,"id_case":246},{"id":51,"id_joueur":3,"id_case":255},{"id":52,"id_joueur":3,"id_case":256},{"id":69,"id_joueur":3,"id_case":345},{"id":70,"id_joueur":3,"id_case":346},{"id":71,"id_joueur":3,"id_case":355},{"id":72,"id_joueur":3,"id_case":356},{"id":89,"id_joueur":3,"id_case":445},{"id":90,"id_joueur":3,"id_case":446},{"id":91,"id_joueur":3,"id_case":455},{"id":92,"id_joueur":3,"id_case":456},{"id":109,"id_joueur":3,"id_case":545},{"id":110,"id_joueur":3,"id_case":546},{"id":111,"id_joueur":3,"id_case":555},{"id":112,"id_joueur":3,"id_case":556},{"id":129,"id_joueur":3,"id_case":645},{"id":130,"id_joueur":3,"id_case":646},{"id":131,"id_joueur":3,"id_case":655},{"id":132,"id_joueur":3,"id_case":656},{"id":149,"id_joueur":3,"id_case":745},{"id":150,"id_joueur":3,"id_case":746},{"id":151,"id_joueur":3,"id_case":755},{"id":152,"id_joueur":3,"id_case":756},{"id":169,"id_joueur":3,"id_case":845},{"id":170,"id_joueur":3,"id_case":846},{"id":171,"id_joueur":3,"id_case":855},{"id":172,"id_joueur":3,"id_case":856},{"id":189,"id_joueur":3,"id_case":945},{"id":190,"id_joueur":3,"id_case":946},{"id":191,"id_joueur":3,"id_case":955},{"id":192,"id_joueur":3,"id_case":956},{"id":209,"id_joueur":3,"id_case":1045},{"id":210,"id_joueur":3,"id_case":1046},{"id":211,"id_joueur":3,"id_case":1055},{"id":212,"id_joueur":3,"id_case":1056},{"id":229,"id_joueur":3,"id_case":1145},{"id":230,"id_joueur":3,"id_case":1146},{"id":231,"id_joueur":3,"id_case":1155},{"id":232,"id_joueur":3,"id_case":1156},{"id":249,"id_joueur":3,"id_case":1245},{"id":250,"id_joueur":3,"id_case":1246},{"id":251,"id_joueur":3,"id_case":1255},{"id":252,"id_joueur":3,"id_case":1256},{"id":269,"id_joueur":3,"id_case":1345},{"id":270,"id_joueur":3,"id_case":1346},{"id":271,"id_joueur":3,"id_case":1355},{"id":272,"id_joueur":3,"id_case":1356},{"id":289,"id_joueur":3,"id_case":1445},{"id":290,"id_joueur":3,"id_case":1446},{"id":291,"id_joueur":3,"id_case":1455},{"id":292,"id_joueur":3,"id_case":1456},{"id":13,"id_joueur":4,"id_case":81},{"id":14,"id_joueur":4,"id_case":82},{"id":15,"id_joueur":4,"id_case":91},{"id":16,"id_joueur":4,"id_case":92},{"id":33,"id_joueur":4,"id_case":181},{"id":34,"id_joueur":4,"id_case":182},{"id":35,"id_joueur":4,"id_case":191},{"id":36,"id_joueur":4,"id_case":192},{"id":53,"id_joueur":4,"id_case":281},{"id":54,"id_joueur":4,"id_case":282},{"id":55,"id_joueur":4,"id_case":291},{"id":56,"id_joueur":4,"id_case":292},{"id":73,"id_joueur":4,"id_case":381},{"id":74,"id_joueur":4,"id_case":382},{"id":75,"id_joueur":4,"id_case":391},{"id":76,"id_joueur":4,"id_case":392},{"id":93,"id_joueur":4,"id_case":481},{"id":94,"id_joueur":4,"id_case":482},{"id":95,"id_joueur":4,"id_case":491},{"id":96,"id_joueur":4,"id_case":492},{"id":113,"id_joueur":4,"id_case":581},{"id":114,"id_joueur":4,"id_case":582},{"id":115,"id_joueur":4,"id_case":591},{"id":116,"id_joueur":4,"id_case":592},{"id":133,"id_joueur":4,"id_case":681},{"id":134,"id_joueur":4,"id_case":682},{"id":135,"id_joueur":4,"id_case":691},{"id":136,"id_joueur":4,"id_case":692},{"id":153,"id_joueur":4,"id_case":781},{"id":154,"id_joueur":4,"id_case":782},{"id":155,"id_joueur":4,"id_case":791},{"id":156,"id_joueur":4,"id_case":792},{"id":173,"id_joueur":4,"id_case":881},{"id":174,"id_joueur":4,"id_case":882},{"id":175,"id_joueur":4,"id_case":891},{"id":176,"id_joueur":4,"id_case":892},{"id":193,"id_joueur":4,"id_case":981},{"id":194,"id_joueur":4,"id_case":982},{"id":195,"id_joueur":4,"id_case":991},{"id":196,"id_joueur":4,"id_case":992},{"id":213,"id_joueur":4,"id_case":1081},{"id":214,"id_joueur":4,"id_case":1082},{"id":215,"id_joueur":4,"id_case":1091},{"id":216,"id_joueur":4,"id_case":1092},{"id":233,"id_joueur":4,"id_case":1181},{"id":234,"id_joueur":4,"id_case":1182},{"id":235,"id_joueur":4,"id_case":1191},{"id":236,"id_joueur":4,"id_case":1192},{"id":253,"id_joueur":4,"id_case":1281},{"id":254,"id_joueur":4,"id_case":1282},{"id":255,"id_joueur":4,"id_case":1291},{"id":256,"id_joueur":4,"id_case":1292},{"id":273,"id_joueur":4,"id_case":1381},{"id":274,"id_joueur":4,"id_case":1382},{"id":275,"id_joueur":4,"id_case":1391},{"id":276,"id_joueur":4,"id_case":1392},{"id":293,"id_joueur":4,"id_case":1481},{"id":294,"id_joueur":4,"id_case":1482},{"id":295,"id_joueur":4,"id_case":1491},{"id":296,"id_joueur":4,"id_case":1492},{"id":17,"id_joueur":5,"id_case":89},{"id":18,"id_joueur":5,"id_case":90},{"id":19,"id_joueur":5,"id_case":99},{"id":20,"id_joueur":5,"id_case":100},{"id":37,"id_joueur":5,"id_case":189},{"id":38,"id_joueur":5,"id_case":190},{"id":39,"id_joueur":5,"id_case":199},{"id":40,"id_joueur":5,"id_case":200},{"id":57,"id_joueur":5,"id_case":289},{"id":58,"id_joueur":5,"id_case":290},{"id":59,"id_joueur":5,"id_case":299},{"id":60,"id_joueur":5,"id_case":300},{"id":77,"id_joueur":5,"id_case":389},{"id":78,"id_joueur":5,"id_case":390},{"id":79,"id_joueur":5,"id_case":399},{"id":80,"id_joueur":5,"id_case":400},{"id":97,"id_joueur":5,"id_case":489},{"id":98,"id_joueur":5,"id_case":490},{"id":99,"id_joueur":5,"id_case":499},{"id":100,"id_joueur":5,"id_case":500},{"id":117,"id_joueur":5,"id_case":589},{"id":118,"id_joueur":5,"id_case":590},{"id":119,"id_joueur":5,"id_case":599},{"id":120,"id_joueur":5,"id_case":600},{"id":137,"id_joueur":5,"id_case":689},{"id":138,"id_joueur":5,"id_case":690},{"id":139,"id_joueur":5,"id_case":699},{"id":140,"id_joueur":5,"id_case":700},{"id":157,"id_joueur":5,"id_case":789},{"id":158,"id_joueur":5,"id_case":790},{"id":159,"id_joueur":5,"id_case":799},{"id":160,"id_joueur":5,"id_case":800},{"id":177,"id_joueur":5,"id_case":889},{"id":178,"id_joueur":5,"id_case":890},{"id":179,"id_joueur":5,"id_case":899},{"id":180,"id_joueur":5,"id_case":900},{"id":197,"id_joueur":5,"id_case":989},{"id":198,"id_joueur":5,"id_case":990},{"id":199,"id_joueur":5,"id_case":999},{"id":200,"id_joueur":5,"id_case":1000},{"id":217,"id_joueur":5,"id_case":1089},{"id":218,"id_joueur":5,"id_case":1090},{"id":219,"id_joueur":5,"id_case":1099},{"id":220,"id_joueur":5,"id_case":1100},{"id":237,"id_joueur":5,"id_case":1189},{"id":238,"id_joueur":5,"id_case":1190},{"id":239,"id_joueur":5,"id_case":1199},{"id":240,"id_joueur":5,"id_case":1200},{"id":257,"id_joueur":5,"id_case":1289},{"id":258,"id_joueur":5,"id_case":1290},{"id":259,"id_joueur":5,"id_case":1299},{"id":260,"id_joueur":5,"id_case":1300},{"id":277,"id_joueur":5,"id_case":1389},{"id":278,"id_joueur":5,"id_case":1390},{"id":279,"id_joueur":5,"id_case":1399},{"id":280,"id_joueur":5,"id_case":1400},{"id":297,"id_joueur":5,"id_case":1489},{"id":298,"id_joueur":5,"id_case":1490},{"id":299,"id_joueur":5,"id_case":1499},{"id":300,"id_joueur":5,"id_case":1500}],"nb_armees":300}

**Comment by AntoineAugusti** [comment]
La base de données a pas dû être réinitialisée. Tu peux essayer de te
connecter au serveur, puis en sudo et /var/www/pullAPI.sh

Keep me posted

**Comment by nat93-dev** [comment]
ça marche je fais ça ! le cleanDB ne permet pas de le faire ?

**Comment by AntoineAugusti** [comment]
Je sais plus ce que fait le script. Mais tu peux essayer ça initialement,
puis la méthode hard

Antoine Augusti
www.antoine-augusti.fr

**Comment by nat93-dev** [comment]
C'est tout bon merci avec pullAPI ! Mais c'est un comportement normal ?

**Comment by AntoineAugusti** [comment]
Ce que tu me demandes c'est si cleanDB devrait nettoyer ça aussi ? Tu l'as
lancé plusieurs fois avant et ça nettoyait bien le reste mais pas ça, c'est
ça ?

Antoine Augusti
www.antoine-augusti.fr

**Comment by nat93-dev** [comment]
Oui c'est ça je lance cleanDB super souvent mais ça ne clean pas les armees. Je me demandais si cleanDB ne devrait pas clean les armees aussi.

**Comment by AntoineAugusti** [comment]
Je modifierai le comportement. Sinon tu peux essayer de fixer ça en
t'inspirant de pullAPI.sh

Antoine Augusti
www.antoine-augusti.fr

**Comment by nat93-dev** [comment]
Ok c'est ça ? 
php artisan clear-compiled
php artisan migrate:reset --force
php artisan migrate --force
php artisan db:seed --force

Et pour wipe les conversations ?

**Comment by AntoineAugusti** [comment]
Supprime et touch la DB

Antoine Augusti
www.antoine-augusti.fr

**Comment by nat93-dev** [comment]
Elle se trouve où ?

**Comment by nat93-dev** [comment]
Found it
