### ISSUE TITLE
endpoint conversations/:id

### ISSUE THREAD

**Issue by nat93-dev** [AntoineAugusti/diplo#32]
On postait auparavant des messages ne comportant qu'un seul mot du genre "salutçava".
Maintenant @jeanclaudeb gère les espaces, l'envoi d'un message fonctionne mais lorsque l'on appelle conversations/:id, on a l'erreur suivante : 

[2015-05-09 18:51:24] local.ERROR: exception 'UnexpectedValueException' with message 'The Response content must be a string or object implementing __toString(), "boolean" given.' in /var/www/api/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php:403
Stack trace:
#0 /var/www/api/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/JsonResponse.php(173): Symfony\Component\HttpFoundation\Response->setContent(false)
#1 /var/www/api/vendor/laravel/framework/src/Illuminate/Http/JsonResponse.php(53): Symfony\Component\HttpFoundation\JsonResponse->update()
#2 /var/www/api/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/JsonResponse.php(49): Illuminate\Http\JsonResponse->setData(Array)
#3 /var/www/api/vendor/laravel/framework/src/Illuminate/Http/JsonResponse.php(29): Symfony\Component\HttpFoundation\JsonResponse->__construct(Array, 200, Array)
#4 /var/www/api/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(87): Illuminate\Http\JsonResponse->__construct(Array, 200, Array, 0)
#5 /var/www/api/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(213): Illuminate\Routing\ResponseFactory->json(Array, 200)
#6 /var/www/api/app/Http/Controllers/ConversationsController.php(68): Illuminate\Support\Facades\Facade::__callStatic('json', Array)
#7 /var/www/api/app/Http/Controllers/ConversationsController.php(68): Illuminate\Support\Facades\Response::json(Array, 200)
#8 [internal function]: Diplo\Http\Controllers\ConversationsController->getConversation(Object(Diplo\Messages\Conversation))
#9 /var/www/api/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(246): call_user_func_array(Array, Array)
#10 /var/www/api/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(162): Illuminate\Routing\Controller->callAction('getConversation', Array)
#11 /var/www/api/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(107): Illuminate\Routing\ControllerDispatcher->call(Object(Diplo\Http\Controllers\ConversationsController), Object(Illuminate\Routing\Route), 'getConversation')
#12 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing{closure}(Object(Illuminate\Http\Request))
#13 /var/www/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#14 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#15 /var/www/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(101): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#16 /var/www/api/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(108): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#17 /var/www/api/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(67): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(Diplo\Http\Controllers\ConversationsController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'getConversation')
#18 /var/www/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(204): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Diplo\Http\Connn...' 'getConversation')
#19 /var/www/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(134): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#20 /var/www/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(701): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#21 [internal function]: Illuminate\Routing\Router->Illuminate\Routing{closure}(Object(Illuminate\Http\Request))
#22 /var/www/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#23 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#24 /var/www/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(101): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#25 /var/www/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(703): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#26 /var/www/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(670): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#27 /var/www/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#28 /var/www/api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(214): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#29 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http{closure}(Object(Illuminate\Http\Request))
#30 /var/www/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#31 /var/www/api/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(55): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#32 /var/www/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 /var/www/api/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(61): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#34 /var/www/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /var/www/api/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(36): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#36 /var/www/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /var/www/api/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(40): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#38 /var/www/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 /var/www/api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(42): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#40 /var/www/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#42 /var/www/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(101): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#43 /var/www/api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(115): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#44 /var/www/api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(84): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#45 /var/www/api/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#46 {main}

**Comment by nat93-dev** [comment]
ping @ThibaudDauce @etiennebatise

**Comment by AntoineAugusti** [comment]
Assigne-moi sur ça. Donne-moi le message envoyé et si possible les appels
faits avant que je retrouve l'état de la base de données

**Comment by AntoineAugusti** [comment]
Dis-moi dans quel cas ça fonctionnait aussi s'il te plaît

**Comment by jeanclaudeb** [comment]
Quand on envoyait une String sans espace.

**Comment by AntoineAugusti** [comment]
Plus de détails SVP. Ce qui a été fait comme requêtes avant, avec les
textes précis, la requête qui a été faites, le résultat obtenu, le résultat
attendu, l'erreur affichée.

Essayez de reproduire si possible

Antoine Augusti
www.antoine-augusti.fr

**Comment by AntoineAugusti** [comment]
Si @ThibaudDauce tu peux regarder en attendant que je rentre à la maison

Antoine Augusti
www.antoine-augusti.fr

**Comment by ThibaudDauce** [comment]
J'ai fait un peu de refactoring mais je ne vois pas bien ce qui peut bugger...

**Comment by AntoineAugusti** [comment]
J'ai vu le refactoring, je ne vois pas trop non plus ce qui peut poser
problème. Je regarde en rentrant dans 20 minutes

Antoine Augusti
www.antoine-augusti.fr

**Comment by ThibaudDauce** [comment]
C'est trop bizarre comme erreur, je ne pense pas que ça vienne des espaces ou non dans les chaînes de caractères...
