### ISSUE TITLE
Doc final

### ISSUE THREAD

**Issue by nat93-dev** [AntoineAugusti/diplo#34]
ping @AntoineAugusti @ThibaudDauce @etiennebatise @manonansart 

Merci de vérifier cet élément du rendu : 

http://p-w.fr/2v3y7

**Comment by AntoineAugusti** [comment]
Vous êtes trop forts les mecs ! Dommage que le texte soit un peu petit,
mais ça rend super !

JC, pense à mettre le fichier en HD sur une clé pour la présentation.

Antoine Augusti
www.antoine-augusti.fr

**Comment by nat93-dev** [comment]
Merci :P

**Comment by jeanclaudeb** [comment]
Thanks ! ça marche !

**Comment by etiennebatise** [comment]
:+1: :+1: :+1:
