### ISSUE TITLE
Respect convention PSR-2

### ISSUE THREAD

**Issue by AntoineAugusti** [AntoineAugusti/diplo#5]
Pour respecter la convention PSR-2 de développement pour PHP : 
- Télécharger https://github.com/FriendsOfPHP/PHP-CS-Fixer
- Le lancer avant de commit `php-cs-fixer fix app` depuis `application/serveur`

**Comment by AntoineAugusti** [comment]
@jeanclaudeb @NathanMalo L'un de vous pourrait regarder un outil équivalent en Java ? Ça permet d'adhérer à une convention de code super facilement. Je lui dis mon dossier où est mon code, il modifie tout ce qui va pas pour respecter la convention (espaces manquants, en trop, sauts de ligne...), sans rien casser, avec une commande. Je suis sûr que ça existe en Java

**Comment by jeanclaudeb** [comment]
J'ai trouvé ça : http://sourceforge.net/projects/astyle/
Et ça : http://sourceforge.net/projects/uncrustify/

**Comment by AntoineAugusti** [comment]
Je te laisse tester, mettre ça en place, aider tes collègues et évangéliser
ça ;-)

Antoine Augusti
www.antoine-augusti.fr

**Comment by jeanclaudeb** [comment]
Oki ^^

**Comment by AntoineAugusti** [comment]
@jeanclaudeb Des nouvelles de ça JC ? C'est en place ?

**Comment by jeanclaudeb** [comment]
J'ai pas eu encore le temps avec l'ECAO. Je fais ça le plus vite possible.

2015-05-04 17:14 GMT+02:00 Antoine Augusti notifications@github.com:

**Comment by jeanclaudeb** [comment]
@AntoineAugusti J'ai oublié de te dire que c'est done ! :)

**Comment by AntoineAugusti** [comment]
J'ai vu, faudra le relancer à la fin ;)

## 

Antoine Augusti
www.antoine-augusti.fr

**Comment by jeanclaudeb** [comment]
ça marche ! :)
