### ISSUE TITLE
Cases voisines

### ISSUE THREAD

**Issue by AntoineAugusti** [AntoineAugusti/diplo#6]
Rajouter les identifiants des cases voisines dans la documentation de l'API. https://developers.diplo-lejeu.fr/diplo/1.0/endpoints/parties/GET_parties_id_carte

**Comment by etiennebatise** [comment]
En attente de verification pour la doc 
- https://github.com/AntoineAugusti/diplo/commit/a9a8afa53f644eb590ac1ed6645a3daa0f31d4e4
- Correction ici https://github.com/AntoineAugusti/diplo/commit/ae986818527e265906bbb9c82b96d2ce9d72ebcc

Est ce que je doit coder la méthode `getCarte(Partie $partie)`  dans **PartiesController.php** ?

**Comment by AntoineAugusti** [comment]
@etiennebatise Tu peux essayer si tu te sens chaud ;) @ThibaudDauce et moi on regardera
