### ISSUE TITLE
Générer une carte rectangulaire / carrée

### ISSUE THREAD

**Issue by AntoineAugusti** [AntoineAugusti/diplo#7]
Une carte 15x15. Chaque joueur possède par exemple 4 armées. Chaque joueur commence dans un coin du carré, un (pauvre) joueur commence au milieu.

Écrire un seeder qui génère la carte, place les armées. Le lancer quand tu entends l'événement `PartiePreteACommencer`

**Comment by AntoineAugusti** [comment]
WIP in https://github.com/AntoineAugusti/diplo/commit/59bafe2ece7d35c6637f9dc8e2689eb2ab2aa6aa

**Comment by ThibaudDauce** [comment]
Je ne sais pas du tout si ça marche, et je sais pas trop comment tester ce genre de trucs... (Queue + event c'est jamais facile...)

**Comment by AntoineAugusti** [comment]
@ThibaudDauce Yep, je suis d'accord. Tu peux essayer en mettant à jour du code sur le serveur, en le faisant tourner et voir comment ça réagit. On faire des modifications en local pour que tu balances bien les bons événements et que tu arrives dans l'état que tu veux tester.

**Comment by ThibaudDauce** [comment]
À priori la carte se génère bien comme il faut.

**Comment by AntoineAugusti** [comment]
Bien joué beau gosse. Le prochain endpoint devrait confirmer ça. J'avais du
régler quelques problèmes de null sur les tables pour permettre la création
de la carte.

Antoine Augusti
www.antoine-augusti.fr
