### ISSUE TITLE
403 

### ISSUE THREAD

**Issue by nat93-dev** [AntoineAugusti/diplo#9]
Erreur 403 lors de l'exécution de execTests.sh sur parties/1/rejoindre

**Comment by nat93-dev** [comment]
J'ai commenté la ligne System.out.println(postHttpsContent("https://api.diplo-lejeu.fr/parties/1/rejoindre"));
pour pas péter travis. Il suffit de la décommenter dans le fichier fr.insarouen.asi.diplo.ComTests

**Comment by AntoineAugusti** [comment]
Il faut nécessaire ajouter un User Agent. Pas de problème si je rajoute `httpsConnection.setRequestProperty("User-Agent", "Diplo/1.0");`

Je te laisse modifier.  http://stackoverflow.com/questions/13670692/403-forbidden-with-java-but-not-web-browser
